---
title: "Content"
---

## Course content

The course curriculum contains theory and interactive exercises as outlined in the table below. This is the curriculum for all the OSTE courses and workshops. The teaching material is openly available (see links below).

+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Topic                          | Content                                                                                     | Link to material                                                                                                                                                                                      |
+================================+=============================================================================================+=======================================================================================================================================================================================================+
| Introduction to OS             | General introduction to OS                                                                  | Presentation                                                                                                                                                                                          |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tools and approaches           | Data management plan, data papers and registered reports                                    | Presentation                                                                                                                                                                                          |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                |                                                                                             | Exersice                                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Executable documents with Quarto                                                            | [Presentation](https://github.com/Open-Science-Course/OS-training-material/blob/main/OS_2023/reproducibleDocuments/quarto.pdf)                                                                        |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                |                                                                                             | [BioST\@TS quarto tutorial](https://biostats-r.github.io/biostats/quarto/)                                                                                                                            |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data collection and management | Data collection                                                                             | [Data collection tutorial](https://biostats-r.github.io/biostats/datacollection/)                                                                                                                     |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Data handling                                                                               | [Material](https://github.com/Open-Science-Course/OS-training-material/tree/main/OS_2023/dataHandling)                                                                                                |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                | including data cleaning, transformation, best practice coding, making functions and package |                                                                                                                                                                                                       |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data repositories              | Data discovery and access - GBIF                                                            | [Presentation](https://htmlpreview.github.io/?https://github.com/ErikKusch/Homepage/blob/master/content/courses/gbif/GBIFWorkshop_LivingNorway_presentation.html) (be patient this takes 10s to load) |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                |                                                                                             | [Exercise](https://www.erikkusch.com/courses/gbif/)                                                                                                                                                   |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | FAIR and CARE data Principles - GBIF                                                        |                                                                                                                                                                                                       |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | FAIR Digital Objects - GBIF                                                                 |                                                                                                                                                                                                       |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Living Norway R package to publish data                                                     | Material                                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reproducible workflows         | Reproducible workflows - targets                                                            | [Presentation](https://github.com/Open-Science-Course/OS-training-material/blob/main/OS_2023/reproducibleWorkflows/targets.pdf)                                                                       |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                |                                                                                             | [BioST\@TS targets tutorial](https://biostats-r.github.io/biostats/targets/)                                                                                                                          |
|                                |                                                                                             |                                                                                                                                                                                                       |
|                                |                                                                                             | Reproducibility exercise                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Version control                                                                             | [BioST\@TS targets tutorial](https://biostats-r.github.io/biostats/github/)                                                                                                                           |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Best practise in data analysis                                                              | [Material](https://github.com/Open-Science-Course/OS-training-material/tree/main/OS_2023/bestPracticeAnalysis)                                                                                        |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                | Best practise for reporting scientific results                                              | [Material](https://github.com/Open-Science-Course/OS-training-material/tree/main/OS_2023/bestPracticeResults)                                                                                         |
+--------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Other resources

-   [BES guides](https://www.britishecologicalsociety.org/publications/guides-to/) The British Ecological Society has a series of guides to research excellence on topics like data management, reproducible coding and more.
-   [BioST\@TS](https://biostats-r.github.io/biostats/) BioST\@TS is an online platform with everything you need to know to write your thesis in R.
